### ISSUE TITLE
command to allow bot to join vc in any server?

### ISSUE THREAD

**Issue by rR31N** [leinstay/discobot#8]
this shouldn't have been posted as an issue since its a suggestion or question
Is there a way to actually make the bot join any VC in any guild instead of staying in one VC in one server?

**Comment by leinstay** [comment]
Any Discord user, including bots, can only be in one voice room on one server at a time. If you are talking about multiple bots, they connect to different servers in the same way as one. You need to boot two bots, two scripts and specify the appropriate voice channel IDs.
